### ISSUE TITLE
Implement a Simple Substitution Cipher

### ISSUE THREAD

**Issue by fa7ad** [fa7ad/bad-ciphers#3]
Conceptually very similar to an XOR cipher (XOR is a type of simple substitution cipher).

Simple substitution ciphers usually replace each character with another predefined character.

There are more complex versions like Homophonic Substitution Ciphers, Polygraphic Substitution Ciphers, etc; but for this issue a simple version should be okay.

More details about the specifics of Substitution cipher can be found on [Wikipedia](https://en.wikipedia.org/wiki/Substitution_cipher)

The implementation should stylistically match the existing code (XOR, for example).

**Comment by inclinedadarsh** [comment]
Heyy! I would like to work on this issue.
Can you please assign this to me?

**Comment by fa7ad** [comment]
Sure, Good Luck!
